# docker-compose.yml
version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: vitivinicultura
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: exemplo
      POSTGRES_INITDB_ARGS: >-
        --encoding=UTF-8
        --lc-collate=pt_BR.UTF-8
        --lc-ctype=pt_BR.UTF-8
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  